# Configuration Explanation:
# (options)
#   (disableNPC) Should we disable viewing the NPC's profile?
#   (disableInCombat)
#     (enabled) Should we prevent player from opening profile while in combat?
#     (message) The message that will be sent if player trying to open profile while in combat
#   (shiftClick) Should player open profile by shift clicking?
#                If disabled, right click will open player profile
options:
  disableNPC: true #Disable player from viewing NPC profile.
  disableInCombat:
    enabled: true
    message: "{prefix} &cYou are not allowed to open profile while in combat!"
  shiftClick: true

# This feature is to auto update the placeholder on every item
# Configuration Explanation:
# (autoRefresh)
#   (enabled) Should we enabled this feature?
#   (refreshEvery) How often should we update the item? (Time is in ticks - 20 ticks = 1 second)
autoRefresh:
  enabled: true
  refreshEvery: 20

# This feature is to give player cooldown to open profiles
# (cooldown)
#   (enabled) Should we enable this feature?
#   (duration) How long is the cooldown? (Time in second)
#   (message) Message that will be sent if player trying to open profile while on cooldown
cooldown:
  enabled: true
  duration: 3 #in seconds
  message: "{prefix} &cPlease wait for another {time} second(s)!"

# Aliases for commands in this plugin
# Configuration Explanation:
# (commandAliases)
#   (playerProfiles) Aliases for /playerprofiles command (main command)
#   (profile) Aliases for /profile command
#   (lockProfile) Aliases for /lockprofile command
#   (unlockProfile) Aliases for /unlockprofile command
commandAliases:
  playerProfiles:
    - 'playerprofile'
    - 'playerp'
    - 'pp'
  profile:
    - 'viewprofile'
    - 'p'
  lockProfile:
    - 'profilelock'
    - 'lock'
  unlockProfile:
    - 'profileunlock'
    - 'unlock'

# If the world name is in the list and players location is inside
# the world that are on the list, player are unable to open any player profiles
# Note: The world name is case sensitive
disabledWorlds:
  message: "{prefix} &cYou are not allowed to open profile in this world!"
  worlds:
    - 'pvpWorld'
    - 'testWorld'

# If the region name is in this list, player are unable to
# open other's player profile with condition if the player/others location
# is inside the disable regions (the region name is case-sensitive)
disabledRegions:
  playerInDisabledRegionMessage: "{prefix} &cYou are not allowed to open profile in this region!"
  targetInDisabledRegionMessage: "{prefix} &cThe target is in disabled region area!"
  regions:
    - 'disabledRegions'

# This feature is to check between player1 (the player) and player2 (the target) location distance
# if the distance is greater than the configured distance - player1 will close the profile inventory
# Configuration Explanation:
# (distanceCheck)
#   (enabled) Should we enabled this feature?
#   (distance) The maximum distance (number is in blocks)
#   (tooFarMessage) Message if the distance is greater than the configured distance
distanceCheck:
  enabled: true
  distance: 30
  tooFarMessage: "{prefix} &e{player} &cis too far from you!"

sounds:
  onProfileOpen:
    enabled: true
    sound: BLOCK_LAVA_POP
    volume: 1
    pitch: 1

messages:
  prefix: '&6&l[!]'
  disabled-worlds: "%prefix% &cYou can't view players profiles on this world!"
  in-combat: "%prefix% &cYou can't open players profiles while in combat!"
  target-not-found: "%prefix% &cTarget is not online!"
  help:
    - "&6Player Profiles &7- by aglerr"
    - "&6/playerprofiles help &7- brings up this messages."
    - "&6/playerprofiles reload &7- reload the configuration."
    - "&6/playerprofiles toggle &7- block/unblock someone from viewing your profile."
    - "&6/playerprofiles creategui <name> &7- create a new gui."
    - "&6/playerprofiles deletegui <name> &7- delete a specific gui."
    - "&6/playerprofiles opengui <name> [player] &7- open a gui."
    - "&6/playerprofiles listgui &7- shows a list of loaded gui."
  help-player:
    - "&6Player Profiles &7- by aglerr"
    - "&6/playerprofiles help &7- bring this help messages."
    - "&6/playerprofiles toggle &7- block/unblock someone from viewing your profile."
  reload: "%prefix% &aYou have successfully reloaded the plugin."
  open-message: "%prefix% &aYou have opened &e%player_name% &aprofiles!"
  on-cooldown: "%prefix% &cYou need to wait &e%time% seconds &cremaining!"
  profileLocked: "%prefix% &cThat player profile is blocked!"
  lockProfile:
    - "&f"
    - "%prefix% &fYou have &c&lLOCKED &fyour profile!"
    - "%prefix% &7No one can see your profile now."
    - "&f"
  unlockProfile:
    - "&f"
    - "%prefix% &fYou have &a&lUNLOCK &fyour profile!"
    - "%prefix% &7Everyone can see your profile now."
    - "&f"
  createGUI: "%prefix% &aYou have successfully created a new GUI called &e%guiName%"
  deleteGUI: "%prefix% &cYou have successfully deleted a GUI called &e%guiName%"
  guiAlreadyExist: "%prefix% &cA GUI called &e%guiName% &cis already exists!"
  guiNotFound: "%prefix% &cCould not find any GUI called &e%guiName%&c."
  listFiles: "%prefix% &fLoaded GUIs: &a%files%"
  noPermission: "%prefix% &cYou are lacking permission &f%permission%"
  invalidUsage: "%prefix% &cInvalid usage: %usage%"
  differentWorld: "%prefix% &cYou are on different world with &e%player%&a."
  blockedProfile: "%prefix% &cYou cannot see this player profile!"