name: PlayerProfiles
version: 6.0.1
main: me.aglerr.playerprofiles.PlayerProfiles
author: aglerr
description: Plugin to show player profiles
api-version: 1.13
softdepend: [CombatLogX, DeluxeCombat, PlaceholderAPI, WorldGuard, WorldEdit]

commands:
  playerprofiles:
    aliases: []
  profile:
    aliases: []
  unlockProfile:
    aliases: []
  lockProfile:
    aliases: []