name: PlayerProfiles
version: 5.7
main: me.aglerr.playerprofiles.Profiles
author: aglerr
description: Plugin to show player profiles
api-version: 1.13
depend: [PlaceholderAPI]
softdepend: [CombatLogX, DeluxeCombat]

commands:
  profile:
    aliases: [profiles]
  playerprofiles: